-- Storage bucket for celebration cover photos and message media.
-- Run after the project is created. Read is public; writes go via signed URLs
-- generated by the service role, so no public write policies are needed.

insert into storage.buckets (id, name, public)
values ('celebrations', 'celebrations', true)
on conflict (id) do nothing;

-- Public read of objects in this bucket.
create policy "celebrations public read"
  on storage.objects for select
  to anon, authenticated
  using (bucket_id = 'celebrations');
